d3.jsonp=function(h,j){var d;if(d=h.match(/callback=d3.jsonp.(\w+)/))d=d[1];else{d="";for(var g=-1;15>++g;)d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(Math.floor(52*Math.random()))}var k=d;d3.jsonp[k]=function(d){j(d);delete d3.jsonp[k];l.remove()};d="d3.jsonp."+k;var l=d3.select("head").append("script").attr("type","text/javascript").attr("src",h.replace(/(\{|%7B)callback(\{|%7D)/,d))};
var genomeBrowser=function(){var h="human",j=7,d=139424940,g=141784100,k,l=[],p=/^(\w+):(\d+)-(\d+)$/,f,q=!1,m=600,n,r,e,s,t,c=function(b){d3.select(b).attr("class","genomeBrowserDiv");f=d3.select(b).attr("id");if(q){var a=d3.select(b).append("p").text("Gene name");a.append("input").attr("id",f+"_gene_name").attr("type","text").attr("name","gene");a.append("input").attr("type","button").attr("value","Jump!").on("click",function(){d3.select("#"+f+"_gene_select").remove();var a=document.getElementById(f+
"_gene_name").value;a.match(p)?(a=p.exec(a),j=a[1],d=a[2],g=a[3],k=void 0,c.start()):c.get_gene(document.getElementById(f+"_gene_name").value,e)});a.append("text").text("(example: ENSG00000139618,  SNORD73 or 5:1533225-1555555)")}var e=d3.select(b).append("div").attr("class","ensGene_selection"),a=d3.select(b).append("div").attr("class","loc_row");a.append("span").text("Current location: "+h+" (");a.append("span").attr("id",f+"_chr").text(j);a.append("span").text(":");a.append("span").attr("id",f+
"_from").text(d);a.append("span").text("-");a.append("span").attr("id",f+"_to").text(g);a.append("span").text(")");b=d3.select(b).append("div").attr("class","groupDiv");n=b.append("svg").attr("class","genomeBrowser").attr("width",m).attr("height",150).append("g").attr("transform","translate(0,20)").append("g").attr("class","gbrowser");b.append("div").attr("id",f+"_gene_info").attr("class","gene_info").style("top",function(){return"60px"});r=n.append("rect").attr("class","pane").attr("width",m).attr("height",
150);void 0!==k?c.get_gene(k,e):c.start()};c.start=function(){var b=c.url();console.log(b);d3.jsonp(b,function(a){l=a;c.plot();c.update()})};c.plot=function(){e=d3.scale.linear().domain([d,g]).range([0,m]);s=d3.svg.axis().scale(e).orient("top");r.call(d3.behavior.zoom().x(e).on("zoom",c.zoom))};c.update=function(){n.call(s);var b=n.selectAll(".gene").data(l,function(a){return a.ID}).attr("x",function(a){return e(a.start)}).attr("width",function(a){return e(a.end)-e(a.start)});b.enter().append("rect").attr("class",
"gene").attr("x",function(a){return e(a.start)}).attr("y",10).attr("width",function(a){return e(a.end)-e(a.start)}).attr("height",10).attr("fill","#F8FBEF").transition().duration(500).attr("fill","black");b.exit().remove();b.on("mouseover",function(a){d3.select(this).transition().duration(300).attr("fill","orange");d3.select("#"+f+"_gene_info").append("p").html(function(){return a.ID+"<br />"+a.external_name+"<br />"+a.description+"<br />"+a.logic_name+"<br />"+a.feature_type+"<br />loc: "+a.seq_region_name+
":"+a.start+"-"+a.end+" (Strand: "+a.strand+")<br />"})});b.on("mouseout",function(){d3.select(this).transition().duration(300).attr("fill","black");d3.selectAll("#"+f+"_gene_info p").remove()});b=n.selectAll(".name").data(l,function(a){return a.ID}).attr("x",function(a){return e(a.start)});b.enter().append("text").attr("class","name").attr("x",function(a){return e(a.start)}).attr("y",35).attr("fill","white").text(function(a){return a.external_name}).transition().duration(500).attr("fill","black");
b.exit().remove();xScale_domain=e.domain();d3.select("#"+f+"_chr").text(j);d3.select("#"+f+"_from").text(~~xScale_domain[0]);d3.select("#"+f+"_to").text(~~xScale_domain[1])};c.zoom=function(){window.clearTimeout(t);t=window.setTimeout(function(){c.from(~~e.invert(0));c.to(~~e.invert(m));console.log("New Pos:"+d+"-"+g);var b=c.url();console.log(b);d3.jsonp(b,function(a){l=a;c.update()})},300);c.update()};c.get_gene=function(b,a){var d="http://beta.rest.ensembl.org/xrefs/symbol/"+h+"/"+b+".jsonp?object=gene;callback=d3.jsonp."+
c.rand();console.log(d);d3.jsonp(d,function(b){console.log("RESP: ");console.log(b);var d=a.append("select").attr("class",function(){return f+"_gene_select"}).attr("id",function(){return f+"_gene_select"});d.selectAll("option").data(b).enter().append("option").attr("class","gene_option").attr("value",function(a){return a.id}).text(function(a){return a.id});d.on("change",function(){c.ensGene(this.value)});c.ensGene(b[0].id)})};c.ensGene=function(b){b="http://beta.rest.ensembl.org/lookup/"+b+".jsonp?callback=d3.jsonp."+
c.rand();console.log(b);d3.jsonp(b,function(a){console.log(a);a.start=32889611;a.end=32973805;a.chr=13;c.chr(a.chr).from(a.start).to(a.end);c.start()});return c};c.searchBox=function(b){q=b;return c};c.width=function(b){if(!arguments.length)return m;m=b;return c};c.from=function(b){if(!arguments.length)return d;d=b;return c};c.to=function(b){if(!arguments.length)return g;g=b;return c};c.species=function(b){if(!arguments.length)return h;h=b;return c};c.chr=function(b){if(!arguments.length)return j;
j=b;return c};c.gene=function(b){if(!arguments.length)return gene_name;k=b;return c};c.url=function(){return"http://beta.rest.ensembl.org/feature/region/"+h+"/"+j+":"+d+"-"+g+".jsonp?feature=gene;callback=d3.jsonp."+c.rand()};c.rand=function(){for(var b="",a=-1;15>++a;)b+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(Math.floor(52*Math.random()));return b};return c};
