d3.jsonp=function(j,k){var d;if(d=j.match(/callback=d3.jsonp.(\w+)/))d=d[1];else{d="";for(var h=-1;15>++h;)d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(Math.floor(52*Math.random()))}var g=d;d3.jsonp[g]=function(d){k(d);delete d3.jsonp[g];f.remove()};d="d3.jsonp."+g;var f=d3.select("head").append("script").attr("type","text/javascript").attr("src",j.replace(/(\{|%7B)callback(\{|%7D)/,d))};
var genomeBrowser=function(){var j="human",k=7,d=139424940,h=141784100,g=[],f,m=!1,l,n,e,p,q,c=function(){};c.rand=function(){for(var b="",a=-1;15>++a;)b+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(Math.floor(52*Math.random()));return b};c.start=function(){var b=c.url("cback3");console.log(b);d3.jsonp(b,function(a){g=a;c.plot();c.update()})};c.url=function(){return"http://beta.rest.ensembl.org/feature/region/"+j+"/"+k+":"+d+"-"+h+".jsonp?feature=gene;callback=d3.jsonp."+c.rand()};
c.plot=function(){e=d3.scale.linear().domain([d,h]).range([0,600]);p=d3.svg.axis().scale(e).orient("top");n.call(d3.behavior.zoom().x(e).on("zoom",c.zoom));c.update=function(){l.call(p);var b=l.selectAll(".gene").data(g,function(a){return a.ID}).attr("x",function(a){return e(a.start)}).attr("width",function(a){return e(a.end)-e(a.start)});b.enter().append("rect").attr("class","gene").attr("x",function(a){return e(a.start)}).attr("y",10).attr("width",function(a){return e(a.end)-e(a.start)}).attr("height",
10).attr("fill","white").transition().duration(1E3).attr("fill","black");b.exit().remove();b.on("mouseover",function(a){d3.select(this).transition().duration(300).attr("fill","orange");d3.select("#"+f+"_gene_info").append("p").html(function(){console.log(a);return a.ID+"<br />"+a.external_name+"<br />"+a.description+"<br />"+a.logic_name+"<br />"+a.feature_type+"<br />loc: "+a.seq_region_name+":"+a.start+"-"+a.end+" (Strand: "+a.strand+")<br />"})});b.on("mouseout",function(){d3.select(this).transition().duration(300).attr("fill",
"black");d3.selectAll("#"+f+"_gene_info p").remove()});b=l.selectAll(".name").data(g,function(a){return a.ID}).attr("x",function(a){return e(a.start)});b.enter().append("text").attr("class","name").attr("x",function(a){return e(a.start)}).attr("y",35).attr("fill","white").text(function(a){return a.external_name}).transition().duration(1E3).attr("fill","black");b.exit().remove()}};c.zoom=function(){window.clearTimeout(q);q=window.setTimeout(function(){c.from(~~e.invert(0));c.to(~~e.invert(600));console.log("New Pos:"+
d+"-"+h);var b=c.url("cbak1");console.log(b);d3.jsonp(b,function(a){g=a;c.update()})},300);c.update()};c.from=function(b){if(!arguments.length)return d;d=b;return c};c.to=function(b){if(!arguments.length)return h;h=b;return c};c.species=function(b){if(!arguments.length)return j;j=b;return c};c.chr=function(b){if(!arguments.length)return k;k=b;return c};c.rand=function(){for(var b="",a=-1;15>++a;)b+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(Math.floor(52*Math.random()));return b};
c.gene=function(b){b="http://beta.rest.ensembl.org/lookup/"+b+".jsonp?callback=d3.jsonp.cback";console.log(b);d3.jsonp(b,function(a){console.log(a);a.start=32889611;a.end=32973805;a.chr=13;c.chr(a.chr).from(a.start).to(a.end);c.start()});return c};c.searchBox=function(b){m=b;return c};c.div=function(b){if(!arguments.length)return f;f=b;if(m){var a=d3.select("#"+f).append("p").text("Gene name");a.append("input").attr("id",f+"_gene_name").attr("type","text").attr("name","gene");a.append("input").attr("id",
"jump").attr("type","button").attr("value","Jump!").on("click",function(){c.gene(document.getElementById(f+"_gene_name").value)});a.append("text").text("(example: ENSG00000139618)")}l=d3.select("#"+f).attr("class","genomeBrowserDiv").append("svg").attr("class","genomeBrowser").attr("width",600).attr("height",150).append("g").attr("transform","translate(0, 20)").append("g").attr("class","gbrowser");d3.select("#"+f).append("div").attr("id",f+"_gene_info").attr("class",function(){return m?"gene_info_searchBox":
"gene_info"});n=l.append("rect").attr("class","pane").attr("width",600).attr("height",150);return c};return c};
